language: php

git:
  depth: 2

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS health_test;'

install:
  - travis_retry composer install --no-interaction

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.1
    - php: 7.0
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - php artisan env
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - php artisan serve &

script:
  - vendor/bin/phpunit && php artisan dusk
