language: php
dist: trusty
sudo: required

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS health_test;'
  - cp .env.dusk.testing .env

install:
  - travis_retry composer install --no-interaction
  - travis_retry npm install
  - npm run dev

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.2
    - php: 7.1
    - php: 7.0
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan env
  - php artisan serve &

script:
  - vendor/bin/phpunit && php artisan dusk
