#!/usr/bin/env bash
composer install

# npm install
# npm run prod

php artisan migrate --force
php artisan optimize
php artisan cache:clear
php artisan view:clear
php artisan backup:run --only-db

if [ -d "/var/www/health/public" ]; then
    sudo rm -rf /var/www/health/public
fi

# copy folders
sudo cp -vr app/ /var/www/health
sudo cp -vr bootstrap/ /var/www/health
sudo cp -vr config/ /var/www/health
sudo cp -vr database/ /var/www/health
sudo cp -vr public/ /var/www/health
sudo cp -vr resources/ /var/www/health
sudo cp -vr routes/ /var/www/health
sudo cp -vr storage/ /var/www/health
sudo cp -vr vendor/ /var/www/health

# copy files
sudo cp artisan /var/www/health
sudo cp server.php /var/www/health
