#!/usr/bin/env bash
#git stash save "Status" # did a git stash cause there were modified changes :/
git pull origin master # shouldn't prompt for .ssh passphrase

composer install

php artisan migrate --force
php artisan optimize
php artisan cache:clear
php artisan view:clear

npm install
npm run prod
