#!/usr/bin/env bash

# npm install

if [ -d "/var/www/health/public" ]; then
    sudo rm -rf /var/www/health/public
fi

# copy folders
sudo cp -vr public/ /var/www/health
sudo cp -vr storage/ /var/www/health

# change permissions and ownership
sudo chown -R www-data:www-data /var/www/health
find /var/www/health/ -type d -exec sudo chmod 755 '{}' \;
find /var/www/health/ -type f -exec sudo chmod 644 '{}' \;
find /var/www/health/storage -type d -exec sudo chmod 777 '{}' \;
find /var/www/health/storage -type f -exec sudo chmod 766 '{}' \;

# run migrations
cd /var/www/health
cd
